#Site settings:
title: Decentralized Patient Identifiers
description: "An alternative to current industry direction that empowers individuals to access their health information without leaving doors wide open."
author: 
  name: Stephan Baur
  email: comments@murmuriq.net
url: https://murmuriq.github.io/path-4-healthcare-2-did
footer_content: 'Copyright &copy; 2026-2030 MurmurIQ.net and contributors.'

#Build settings:
theme: just-the-docs
#aux_links:
  #Template Repository: https://github.com/just-the-docs/just-the-docs-template

# Enable or disable the side/mobile menu globally
# Nav menu can also be selectively enabled or disabled using page variables or the minimal layout
nav_enabled: true

# Sort order for navigation links
# nav_sort: case_insensitive # default, equivalent to nil
nav_sort: case_sensitive # Capital letters sorted before lowercase
